export const achievements = [
  {
    slug: 'first-speaking',
    name: 'First Words',
    description: 'Complete your very first speaking session',
    icon: '🎙️',
    rarity: 'common',
    condition: { type: 'sessions', value: 1 },
  },
  {
    slug: 'streak-7',
    name: '7-Day Streak',
    description: 'Practice for 7 consecutive days',
    icon: '🔥',
    rarity: 'common',
    condition: { type: 'streak', value: 7 },
  },
  {
    slug: 'streak-30',
    name: '30-Day Streak',
    description: 'Practice for 30 consecutive days',
    icon: '🔥',
    rarity: 'rare',
    condition: { type: 'streak', value: 30 },
  },
  {
    slug: 'streak-100',
    name: 'Century Streak',
    description: 'Practice for 100 consecutive days',
    icon: '💎',
    rarity: 'legendary',
    condition: { type: 'streak', value: 100 },
  },
  {
    slug: 'sessions-10',
    name: 'Getting Started',
    description: 'Complete 10 speaking sessions',
    icon: '⭐',
    rarity: 'common',
    condition: { type: 'sessions', value: 10 },
  },
  {
    slug: 'sessions-50',
    name: 'Consistent Learner',
    description: 'Complete 50 speaking sessions',
    icon: '🎯',
    rarity: 'rare',
    condition: { type: 'sessions', value: 50 },
  },
  {
    slug: 'sessions-100',
    name: 'Speaking Master',
    description: 'Complete 100 speaking sessions',
    icon: '👑',
    rarity: 'epic',
    condition: { type: 'sessions', value: 100 },
  },
  {
    slug: 'vocab-100',
    name: '100 Words Strong',
    description: 'Learn 100 vocabulary words',
    icon: '📚',
    rarity: 'common',
    condition: { type: 'vocabulary', value: 100 },
  },
  {
    slug: 'vocab-500',
    name: 'Vocabulary Builder',
    description: 'Learn 500 vocabulary words',
    icon: '📖',
    rarity: 'rare',
    condition: { type: 'vocabulary', value: 500 },
  },
  {
    slug: 'perfect-score',
    name: 'Perfect Speaker',
    description: 'Score 95 or above in overall score',
    icon: '💯',
    rarity: 'epic',
    condition: { type: 'score', value: 95 },
  },
  {
    slug: 'fluent-3',
    name: 'Fluency Star',
    description: 'Score above 90 in Fluency three times in a row',
    icon: '🗣️',
    rarity: 'rare',
    condition: { type: 'score', value: 90, extra: 'fluency_3x' },
  },
  {
    slug: 'tech-explorer',
    name: 'Tech Explorer',
    description: 'Complete 5 Technology topics',
    icon: '💻',
    rarity: 'common',
    condition: { type: 'category', value: 5, extra: 'technology' },
  },
  {
    slug: 'psychology-explorer',
    name: 'Psychology Explorer',
    description: 'Complete 5 Psychology topics',
    icon: '🧠',
    rarity: 'common',
    condition: { type: 'category', value: 5, extra: 'psychology' },
  },
  {
    slug: 'health-enthusiast',
    name: 'Health Enthusiast',
    description: 'Complete 5 Health topics',
    icon: '❤️',
    rarity: 'common',
    condition: { type: 'category', value: 5, extra: 'health' },
  },
  {
    slug: 'bilingual',
    name: 'Bilingual Speaker',
    description: 'Practice in both English and Indonesian',
    icon: '🌏',
    rarity: 'common',
    condition: { type: 'sessions', value: 1, extra: 'bilingual' },
  },
  {
    slug: 'early-bird',
    name: 'Early Bird',
    description: 'Practice before 8 AM for 5 days',
    icon: '🌅',
    rarity: 'rare',
    condition: { type: 'sessions', value: 5, extra: 'early_bird' },
  },
  {
    slug: 'night-owl',
    name: 'Night Owl',
    description: 'Practice after 10 PM for 5 days',
    icon: '🦉',
    rarity: 'rare',
    condition: { type: 'sessions', value: 5, extra: 'night_owl' },
  },
  {
    slug: 'marathon',
    name: 'Marathon Speaker',
    description: 'Complete a 5-minute speaking session',
    icon: '🏃',
    rarity: 'rare',
    condition: { type: 'sessions', value: 1, extra: 'duration_300' },
  },
]
