export const categories = [
  {
    name: 'Daily Conversation',
    slug: 'daily-conversation',
    icon: '💬',
    description: 'Practice everyday English for real-life situations',
    color: '#6366f1',
    order: 1,
  },
  {
    name: 'Technology',
    slug: 'technology',
    icon: '💻',
    description: 'Discuss tech topics, AI, programming, and digital world',
    color: '#0ea5e9',
    order: 2,
  },
  {
    name: 'Business',
    slug: 'business',
    icon: '💼',
    description: 'Master business English for professional settings',
    color: '#f59e0b',
    order: 3,
  },
  {
    name: 'Health',
    slug: 'health',
    icon: '🏥',
    description: 'Talk about health, nutrition, fitness, and well-being',
    color: '#10b981',
    order: 4,
  },
  {
    name: 'Science',
    slug: 'science',
    icon: '🔬',
    description: 'Explore physics, chemistry, biology, and astronomy',
    color: '#8b5cf6',
    order: 5,
  },
  {
    name: 'Sports',
    slug: 'sports',
    icon: '⚽',
    description: 'Discuss sports, athletes, competitions, and fitness',
    color: '#ef4444',
    order: 6,
  },
  {
    name: 'Education',
    slug: 'education',
    icon: '📚',
    description: 'Talk about learning, subjects, and academic life',
    color: '#f97316',
    order: 7,
  },
  {
    name: 'Psychology',
    slug: 'psychology',
    icon: '🧠',
    description: 'Understand human behavior, biases, and the mind',
    color: '#ec4899',
    order: 8,
  },
  {
    name: 'Art',
    slug: 'art',
    icon: '🎨',
    description: 'Explore painting, music, photography, and design',
    color: '#14b8a6',
    order: 9,
  },
  {
    name: 'Environment',
    slug: 'environment',
    icon: '🌿',
    description: 'Discuss climate change, sustainability, and nature',
    color: '#22c55e',
    order: 10,
  },
  {
    name: 'Random',
    slug: 'random',
    icon: '🎲',
    description: 'Mix of all categories — spin and surprise yourself!',
    color: '#a855f7',
    order: 11,
  },
]
